### ISSUE TITLE
Display current k8s cluster name

### ISSUE THREAD

**Issue by rydogs** [rydogs/kubecle#22]
_From @rliuAsapp on July 8, 2018 15:26_

Display k8s cluster name on header.  Need to figure out how to get this information from k8s client

_Copied from original issue: ASAPPinc/kubecle#3_

**Comment by chadasapp** [comment]
`kubectl cluster-info`?

**Comment by rliuAsapp** [comment]
This is already done.  Library reads it from .kube/config
