### ISSUE TITLE
pods page become non reactive after a while

### ISSUE THREAD

**Issue by rydogs** [rydogs/kubecle#48]
Need to profile and see if there is any memory leak

**Comment by rliuAsapp** [comment]
<img width="1638" alt="screen shot 2018-10-10 at 7 01 33 pm" src="https://user-images.githubusercontent.com/30121162/46770834-fd47e500-ccbe-11e8-9ed0-92b2d0f144e5.png">

**Comment by rydogs** [comment]
Fixed!
